/**
 * ============================================================================
 * PRISMA SEED - DONNÉES INITIALES ACADEMIA HUB
 * ============================================================================
 * 
 * Script de seed pour créer les données initiales indispensables :
 * - Pays BJ (Bénin)
 * - Tenant par défaut (nécessaire pour les autres données)
 * - Année scolaire active (2024-2025)
 * - Niveaux scolaires (Maternelle, Primaire, Secondaire)
 * - Régimes tarifaires STANDARD par niveau
 * 
 * ⚠️ IMPORTANT : Seed idempotent (peut être relancé plusieurs fois)
 * 
 * Usage: npx prisma db seed
 * 
 * ============================================================================
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Démarrage du seed...\n');

  // ============================================================================
  // 1. CRÉER LE PAYS BJ (BÉNIN) - IDEMPOTENT
  // ============================================================================
  console.log('1️⃣  Création du pays BJ (Bénin)...');
  
  const country = await prisma.country.upsert({
    where: { code: 'BJ' },
    update: {},
    create: {
      code: 'BJ',
      name: 'Bénin',
      code3: 'BEN',
      numericCode: '204',
      currencyCode: 'XOF',
      currencySymbol: 'CFA',
      phonePrefix: '+229',
      flagEmoji: '🇧🇯',
      isDefault: true,
      isActive: true,
    },
  });

  console.log(`   ✅ Pays créé: ${country.name} (${country.code})`);

  // ============================================================================
  // 2. CRÉER UN TENANT PAR DÉFAUT - IDEMPOTENT
  // ============================================================================
  // ⚠️ Nécessaire car AcademicYear, SchoolLevel, et FeeRegime nécessitent un tenantId
  console.log('\n2️⃣  Création du tenant par défaut...');
  
  const tenant = await prisma.tenant.upsert({
    where: { slug: 'default-tenant' },
    update: {},
    create: {
      name: 'Tenant par Défaut - Academia Hub',
      slug: 'default-tenant',
      subdomain: 'default',
      countryId: country.id,
      type: 'SCHOOL',
      subscriptionStatus: 'TRIAL',
      status: 'active',
      subscriptionPlan: 'free',
    },
  });

  console.log(`   ✅ Tenant créé: ${tenant.name} (${tenant.slug})`);

  // ============================================================================
  // 3. CRÉER L'ANNÉE SCOLAIRE ACTIVE (2024-2025) - IDEMPOTENT
  // ============================================================================
  console.log('\n3️⃣  Création de l\'année scolaire active (2024-2025)...');
  
  // Dates : Septembre 2024 - Juillet 2025
  const currentYear = new Date().getFullYear();
  const academicYearName = `${currentYear}-${currentYear + 1}`;
  const startDate = new Date(`${currentYear}-09-01`);
  const endDate = new Date(`${currentYear + 1}-07-31`);
  const preEntryDate = new Date(`${currentYear}-09-02`); // Lundi 2ème semaine septembre

  // Vérifier si l'année existe déjà
  let academicYear = await prisma.academicYear.findFirst({
    where: {
      tenantId: tenant.id,
      name: academicYearName,
    },
  });

  if (!academicYear) {
    academicYear = await prisma.academicYear.create({
      data: {
        tenantId: tenant.id,
        name: academicYearName,
        label: `Année scolaire ${academicYearName}`,
        startDate: startDate,
        endDate: endDate,
        preEntryDate: preEntryDate,
        isActive: true,
        isAutoGenerated: false,
      },
    });
    console.log(`   ✅ Année scolaire créée: ${academicYear.label}`);
  } else {
    // Mettre à jour si elle existe mais n'est pas active
    if (!academicYear.isActive) {
      academicYear = await prisma.academicYear.update({
        where: { id: academicYear.id },
        data: { isActive: true },
      });
      console.log(`   ✅ Année scolaire activée: ${academicYear.label}`);
    } else {
      console.log(`   ℹ️  Année scolaire déjà existante: ${academicYear.label}`);
    }
  }

  // ============================================================================
  // 4. CRÉER LES NIVEAUX SCOLAIRES - IDEMPOTENT
  // ============================================================================
  console.log('\n4️⃣  Création des niveaux scolaires...');

  const schoolLevelsData = [
    { code: 'MATERNELLE', name: 'Maternelle', label: 'Maternelle', order: 1 },
    { code: 'PRIMAIRE', name: 'Primaire', label: 'Primaire', order: 2 },
    { code: 'SECONDAIRE', name: 'Secondaire', label: 'Secondaire', order: 3 },
  ];

  const schoolLevels = [];

  for (const levelData of schoolLevelsData) {
    // Utiliser upsert avec la contrainte unique (tenantId, code)
    const schoolLevel = await prisma.schoolLevel.upsert({
      where: {
        tenantId_code: {
          tenantId: tenant.id,
          code: levelData.code,
        },
      },
      update: {},
      create: {
        tenantId: tenant.id,
        code: levelData.code,
        name: levelData.name,
        label: levelData.label,
        order: levelData.order,
      },
    });

    schoolLevels.push(schoolLevel);
    console.log(`   ✅ Niveau créé: ${schoolLevel.label} (${schoolLevel.code})`);
  }

  // ============================================================================
  // 5. CRÉER LES RÉGIMES TARIFAIRES STANDARD - IDEMPOTENT
  // ============================================================================
  console.log('\n5️⃣  Création des régimes tarifaires STANDARD...');

  for (const schoolLevel of schoolLevels) {
    // Vérifier si le régime STANDARD existe déjà pour cette combinaison
    const existingRegime = await prisma.feeRegime.findFirst({
      where: {
        tenantId: tenant.id,
        academicYearId: academicYear.id,
        schoolLevelId: schoolLevel.id,
        code: 'STANDARD',
      },
    });

    if (!existingRegime) {
      const feeRegime = await prisma.feeRegime.create({
        data: {
          tenantId: tenant.id,
          academicYearId: academicYear.id,
          schoolLevelId: schoolLevel.id,
          code: 'STANDARD',
          label: `Régime STANDARD - ${schoolLevel.label}`,
          description: `Régime tarifaire standard pour le niveau ${schoolLevel.label}`,
          isDefault: true,
        },
      });

      console.log(`   ✅ Régime STANDARD créé pour ${schoolLevel.label}`);
    } else {
      console.log(`   ℹ️  Régime STANDARD déjà existant pour ${schoolLevel.label}`);
    }
  }

  // ============================================================================
  // RÉSUMÉ
  // ============================================================================
  console.log('\n' + '='.repeat(60));
  console.log('✅ Seed terminé avec succès!');
  console.log('='.repeat(60));
  console.log('\n📊 Données créées:');
  console.log(`   - Pays: ${country.name} (${country.code})`);
  console.log(`   - Tenant: ${tenant.name}`);
  console.log(`   - Année scolaire: ${academicYear.label}`);
  console.log(`   - Niveaux scolaires: ${schoolLevels.length} (${schoolLevels.map(s => s.label).join(', ')})`);
  console.log(`   - Régimes tarifaires: ${schoolLevels.length} (STANDARD par niveau)`);
  console.log('\n🎯 La base de données est prête à l\'usage!');
}

main()
  .catch((e) => {
    console.error('\n❌ Erreur lors du seed:');
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
